import 'dart:convert';
import 'package:http/http.dart' as http;
import 'api_service.dart';
import 'jprequest.dart';
import 'package:merchandising/pages/Journeyplan.dart';
import 'package:merchandising/model/Location_service.dart';


Future<void> getJourneyPlan() async {
  http.Response JPresponse = await http.post(JPurl,
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': 'Bearer $token',
    },
    body: jsonEncode(DBrequestData),
  );
  if (JPresponse.statusCode == 200){
    print("journeyplandone");
    String JPdata = JPresponse.body;
    var decodeJPData = jsonDecode(JPdata);
    JPResponsePlanneddata.outletiddata1 = decodeJPData['data'][0]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata1 = decodeJPData['data'][0]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata1 = decodeJPData['data'][0]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata1 = decodeJPData['data'][0]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata1 = decodeJPData['data'][0]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata1 = decodeJPData['data'][0]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata1 = decodeJPData['data'][0]['outlet']['outlet_city'];
    JPResponsePlanneddata.id1 = decodeJPData['data'][0]['id'];
    JPResponsePlanneddata.outletiddata2 = decodeJPData['data'][1]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata2 = decodeJPData['data'][1]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata2 = decodeJPData['data'][1]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata2 = decodeJPData['data'][1]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata2 = decodeJPData['data'][1]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata2 = decodeJPData['data'][1]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata2 = decodeJPData['data'][1]['outlet']['outlet_city'];
    JPResponsePlanneddata.id2 = decodeJPData['data'][1]['id'];
    JPResponsePlanneddata.outletiddata3 = decodeJPData['data'][2]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata3 = decodeJPData['data'][2]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata3 = decodeJPData['data'][2]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata3 = decodeJPData['data'][2]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata3 = decodeJPData['data'][2]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata3 = decodeJPData['data'][2]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata3 = decodeJPData['data'][2]['outlet']['outlet_city'];
    JPResponsePlanneddata.id3 = decodeJPData['data'][2]['id'];
    JPResponsePlanneddata.outletiddata4 = decodeJPData['data'][3]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata4 = decodeJPData['data'][3]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata4 = decodeJPData['data'][3]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata4 = decodeJPData['data'][3]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata4 = decodeJPData['data'][3]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata4 = decodeJPData['data'][3]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata4 = decodeJPData['data'][3]['outlet']['outlet_city'];
    JPResponsePlanneddata.id4 = decodeJPData['data'][3]['id'];
    JPResponsePlanneddata.outletiddata5 = decodeJPData['data'][4]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata5 = decodeJPData['data'][4]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata5 = decodeJPData['data'][4]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata5 = decodeJPData['data'][4]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata5 = decodeJPData['data'][4]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata5 = decodeJPData['data'][4]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata5 = decodeJPData['data'][4]['outlet']['outlet_city'];
    JPResponsePlanneddata.id5 = decodeJPData['data'][4]['id'];
    JPResponsePlanneddata.outletiddata6 = decodeJPData['data'][5]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata6 = decodeJPData['data'][5]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata6 = decodeJPData['data'][5]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata6 = decodeJPData['data'][5]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata6 = decodeJPData['data'][5]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata6 = decodeJPData['data'][5]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata6 = decodeJPData['data'][5]['outlet']['outlet_city'];
    JPResponsePlanneddata.id6 = decodeJPData['data'][5]['id'];
    JPResponsePlanneddata.outletiddata7 = decodeJPData['data'][6]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata7 = decodeJPData['data'][6]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata7 = decodeJPData['data'][6]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata7 = decodeJPData['data'][6]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata7 = decodeJPData['data'][6]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata7 = decodeJPData['data'][6]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata7 = decodeJPData['data'][6]['outlet']['outlet_city'];
    JPResponsePlanneddata.id7 = decodeJPData['data'][6]['id'];
    JPResponsePlanneddata.outletiddata8 = decodeJPData['data'][7]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata8 = decodeJPData['data'][7]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata8 = decodeJPData['data'][7]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata8 = decodeJPData['data'][7]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata8 = decodeJPData['data'][7]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata8 = decodeJPData['data'][7]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata8 = decodeJPData['data'][7]['outlet']['outlet_city'];
    JPResponsePlanneddata.id8 = decodeJPData['data'][7]['id'];
    JPResponsePlanneddata.outletiddata9 = decodeJPData['data'][8]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata9 = decodeJPData['data'][8]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata9 = decodeJPData['data'][8]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata9 = decodeJPData['data'][8]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata9 = decodeJPData['data'][8]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata9 = decodeJPData['data'][8]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata9 = decodeJPData['data'][8]['outlet']['outlet_city'];
    JPResponsePlanneddata.id9 = decodeJPData['data'][8]['id'];
    JPResponsePlanneddata.outletiddata10 = decodeJPData['data'][9]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata10 = decodeJPData['data'][9]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata10 = decodeJPData['data'][9]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata10 = decodeJPData['data'][9]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata10 = decodeJPData['data'][9]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata10 = decodeJPData['data'][9]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata10 = decodeJPData['data'][9]['outlet']['outlet_city'];
    JPResponsePlanneddata.id10 = decodeJPData['data'][9]['id'];
    JPResponsePlanneddata.outletiddata11 = decodeJPData['data'][10]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata11 = decodeJPData['data'][10]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata11 = decodeJPData['data'][10]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata11 = decodeJPData['data'][10]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata11 = decodeJPData['data'][10]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata11 = decodeJPData['data'][10]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata11 = decodeJPData['data'][10]['outlet']['outlet_city'];
    JPResponsePlanneddata.id11 = decodeJPData['data'][10]['id'];
    JPResponsePlanneddata.outletiddata12 = decodeJPData['data'][11]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata12 = decodeJPData['data'][11]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata12 = decodeJPData['data'][11]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata12 = decodeJPData['data'][11]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata12 = decodeJPData['data'][11]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata12 = decodeJPData['data'][11]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata12 = decodeJPData['data'][11]['outlet']['outlet_city'];
    JPResponsePlanneddata.id12 = decodeJPData['data'][11]['id'];
    JPResponsePlanneddata.outletiddata13 = decodeJPData['data'][12]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata13 = decodeJPData['data'][12]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata13 = decodeJPData['data'][12]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata13 = decodeJPData['data'][12]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata13 = decodeJPData['data'][12]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata13 = decodeJPData['data'][12]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata13 = decodeJPData['data'][12]['outlet']['outlet_city'];
    JPResponsePlanneddata.id13 = decodeJPData['data'][12]['id'];
    JPResponsePlanneddata.outletiddata14 = decodeJPData['data'][13]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata14 = decodeJPData['data'][13]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata14= decodeJPData['data'][13]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata14 = decodeJPData['data'][13]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata14 = decodeJPData['data'][13]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata14 = decodeJPData['data'][13]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata14 = decodeJPData['data'][13]['outlet']['outlet_city'];
    JPResponsePlanneddata.id14 = decodeJPData['data'][13]['id'];
    JPResponsePlanneddata.outletiddata15 = decodeJPData['data'][14]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata15 = decodeJPData['data'][14]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata15 = decodeJPData['data'][14]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata15 = decodeJPData['data'][14]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata15 = decodeJPData['data'][14]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata15 = decodeJPData['data'][14]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata15 = decodeJPData['data'][14]['outlet']['outlet_city'];
    JPResponsePlanneddata.id15 = decodeJPData['data'][14]['id'];
    JPResponsePlanneddata.outletiddata16 = decodeJPData['data'][15]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata16 = decodeJPData['data'][15]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata16 = decodeJPData['data'][15]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata16 = decodeJPData['data'][15]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata16 = decodeJPData['data'][15]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata16 = decodeJPData['data'][15]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata16 = decodeJPData['data'][15]['outlet']['outlet_city'];
    JPResponsePlanneddata.id16 = decodeJPData['data'][15]['id'];
    JPResponsePlanneddata.outletiddata17 = decodeJPData['data'][16]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata17 = decodeJPData['data'][16]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata17 = decodeJPData['data'][16]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata17 = decodeJPData['data'][16]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata17 = decodeJPData['data'][16]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata17 = decodeJPData['data'][16]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata17 = decodeJPData['data'][16]['outlet']['outlet_city'];
    JPResponsePlanneddata.id17 = decodeJPData['data'][16]['id'];
    JPResponsePlanneddata.outletiddata18 = decodeJPData['data'][17]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata18 = decodeJPData['data'][17]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata18 = decodeJPData['data'][17]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata18 = decodeJPData['data'][17]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata18 = decodeJPData['data'][17]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata18 = decodeJPData['data'][17]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata18 = decodeJPData['data'][17]['outlet']['outlet_city'];
    JPResponsePlanneddata.id18 = decodeJPData['data'][17]['id'];
    JPResponsePlanneddata.outletiddata19 = decodeJPData['data'][18]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata19 = decodeJPData['data'][18]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata19 = decodeJPData['data'][18]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata19 = decodeJPData['data'][18]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata19 = decodeJPData['data'][18]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata19 = decodeJPData['data'][18]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata19 = decodeJPData['data'][18]['outlet']['outlet_city'];
    JPResponsePlanneddata.id19 = decodeJPData['data'][18]['id'];
    JPResponsePlanneddata.outletiddata20 = decodeJPData['data'][19]['outlet']['outlet_id'];
    JPResponsePlanneddata.outletnamedata20 = decodeJPData['data'][19]['outlet']['outlet_name'];
    JPResponsePlanneddata.latitudedata20 = decodeJPData['data'][19]['outlet']['outlet_lat'];
    JPResponsePlanneddata.longitudedata20 = decodeJPData['data'][19]['outlet']['outlet_long'];
    JPResponsePlanneddata.outletareadata20 = decodeJPData['data'][19]['outlet']['outlet_area'];
    JPResponsePlanneddata.outletcountrydata20 = decodeJPData['data'][19]['outlet']['outlet_country'];
    JPResponsePlanneddata.outletcitydata20 = decodeJPData['data'][19]['outlet']['outlet_city'];
    JPResponsePlanneddata.id20 = decodeJPData['data'][19]['id'];
  }
  if(JPresponse.statusCode != 200){
    print(JPresponse.statusCode);
  }
}
